---
# tasks file for prometheus unifi-exporter

- name: unifi group created
  group:
      name: '{{ PROMETHEUS_UNIFI_EXPORTER_GROUP}}'
      state: present

- name: unifi_exporter_user created
  user:
      name: '{{ PROMETHEUS_UNIFI_EXPORTER_USER }}'
      group: '{{ PROMETHEUS_UNIFI_EXPORTER_GROUP}}'
      createhome: false
      shell: '/sbin/nologin'
      state: present

- name: unifi_exporter directories created
  file:
      path: '{{ item }}'
      state: 'directory'
      owner: '{{ PROMETHEUS_UNIFI_EXPORTER_USER }}'
      group: '{{ PROMETHEUS_UNIFI_EXPORTER_GROUP }}'
      mode: 'u=rwx,g=rx,o='
  with_items: '{{ PROMETHEUS_UNIFI_EXPORTER_DIRS.values() }}'

- name: unifi_exporter binary downloaded
  get_url:
      url: '{{ PROMETHEUS_UNIFI_EXPORTER_DL_BASE }}/{{ PROMETHEUS_UNIFI_EXPORTER_BIN_NAME }}'
      dest: '{{ PROMETHEUS_UNIFI_EXPORTER_DIRS.PROMETHEUS_UNIFI_EXPORTER_BIN_DIR  }}'
      checksum: 'sha256:{{ PROMETHEUS_UNIFI_EXPORTER_PACKAGE_CHECKSUM  }}'
      mode: 'u=rwx,g=rx,o='
      owner: '{{ PROMETHEUS_UNIFI_EXPORTER_USER }}'
      group: '{{ PROMETHEUS_UNIFI_EXPORTER_GROUP }}'


- name: unifi_exporter link created
  file:
      path: '/usr/local/bin/unifi_exporter'
      state: 'link'
      src: '{{ PROMETHEUS_UNIFI_EXPORTER_DIRS.PROMETHEUS_UNIFI_EXPORTER_BIN_DIR  }}/{{ PROMETHEUS_UNIFI_EXPORTER_BIN_NAME }}'
      mode: 'u=rwx,g=rx,o='
      owner: '{{ PROMETHEUS_UNIFI_EXPORTER_USER }}'
      group: '{{ PROMETHEUS_UNIFI_EXPORTER_GROUP }}'
